#This code is divided into 2 sections. First, non-specific names are removed. Then, devices which may be referred to by more than 1 name are combined
devfig_df <- devices %>%
  #Remove non-specific names
  filter(!name %in% c("OTHER", "Vascular", "Spine", 
                      "CRM", "HIPS", "Heart Valves",
                      "OTHER- BSC PRODUCT NOT LISTED",
                      "CLINICAL TRIAL PRODUCT",
                      "TRAUMA & EXTREMITIES",
                      "OTHER - MISCELLANEOUS",
                      "Neuro-Chronic Pain",
                      "Thoracolumbar - TL Therapies",
                      "Spinal Cord Neurostimulation - Neuro",
                      "Trauma",
                      "Sports Medicine",
                      "Knees",
                      "Orthopedics",
                      "Stents",
                      "Recon Knees",
                      "Atherectomy Device",
                      "Bradycardia products",
                      "PAIN MANAGEMENT",
                      "ThoracoLumbar",
                      "Joint Implants",
                      "Transcatheter Heart Valves",
                      "Surgical",
                      "OtherNA")) %>%
  #Combine devices referred to by more than 1 name
  filter(name != "" & !(name %>% str_detect("GENERAL") & name %>% str_detect("THERAPIES"))) %>%
  mutate(name = case_when(
    str_detect(name, "(?i)SAPIEN 3") ~ "Sapien 3",
    str_detect(name, "(?i)IFUSE Implant") ~ "iFUSE Implant System",
    str_detect(name, "(?i)Equinoxe") ~ "Equinoxe Platform System",
    str_detect(name, "(?i)Attune") ~ "ATTUNE Knee System",
    str_detect(name, "(?i)Mako") ~ "Mako SmartRobotics",
    str_detect(name, "(?i)Da vinci|(?i)davinci|(?i)Da Vinci") ~ "da Vinci Surgical System",
    str_detect(name, "(?i)IMPELLA") ~ "Impella",
    str_detect(name, "(?i)corevalve evolut") ~ "CoreValve Evolut",
    str_detect(name, "(?i)Watchman") ~ "Watchman",
    str_detect(name, "(?i)LifeVest") ~ "LifeVest", 
    str_detect(name, "(?i)Carto 3|(?i)Carto-3") ~ "Carto 3",
    str_detect(name, "(?i)SQ-RX|(?i)SQ RX|(?i)SQRX") ~ "SQ-RX",
    str_detect(name, "(?i)CardioMEMS|(?i)Cardio MEMS|(?i)Cardio-MEMS") ~ "CardioMEMS",
    str_detect(name, "(?i)Xience V|(?i)XienceV|(?i)Xience-V") ~ "Xience V",
    str_detect(name, "(?i)Mitra Clip|(?i)MitraClip|(?i)Mitra-Clip") ~ "MitraClip",
    str_detect(name, "(?i)Arctic Front|(?i)ArcticFront|(?i)Arctic-Front") ~ "Arctic Front",
    str_detect(name, "(?i)Coronary orbital atherectomy") ~ "Coronary orbital atherectomy",
    str_detect(name, "(?i)Micra") ~ "Micra",
    str_detect(name, "(?i)Resolute") ~ "Resolute",
    str_detect(name, "(?i)xlif") ~ "XLIF",
    str_detect(name, "(?i)Senza spinal cord") ~ "Senza Spinal Cord Stimulation",
    str_detect(name, "(?i)SIR-SPHERES MICROSPHERES") ~ "SIR-Spheres microspheres",
    str_detect(name, "(?i)^senza") ~ "Senza Spinal Cord Stimulation System",
    str_detect(name, "(?i)^cd horizon") ~ "CD Horizon Spinal System",
    str_detect(name, "(?i)^natrelle") ~ "Natrelle Implants",
    str_detect(name, "(?i)^endurant") ~ "Endurant stents",
    str_detect(name, "(?i)^expedium") ~ "Expedium Spine System",
    str_detect(name, "(?i)^accolade") ~ "Accolade pacing systems",
    str_detect(name, "(?i)Definity") ~ "Definity",
    str_detect(name, "(?i)Urolift|(?i)UroLift") ~ "UroLift",
    str_detect(name, "(?i)Web aneurysm|(?i) Web embol") ~ "Web Embolization System",
    str_detect(name, "(?i)Proclaim") ~ "PROCLAIM",
    str_detect(name, "(?i)DJO Surg") ~ "DJO Surgical",
    str_detect(name, "(?i)Shockwave IVL") ~ "Shockwave IVL System",
    str_detect(name, "(?i)Flowtriever") ~ "Flowtriever",
    str_detect(name, "(?i)Indigo System") ~ "Indigo System",
    str_detect(name, "(?i)Mazor") ~ "Mazor System",
    str_detect(name, "(?i)Intellis") ~ "Intellis System",
    str_detect(name, "(?i)ROSA") ~ "Rosa System",
    str_detect(name, "(?i)Acessa") ~ "Acessa",
    str_detect(name, "(?i)Epi-sense") ~ "EPi-Sense System",
    str_detect(name, "(?i)Arthrex") ~ "Arthrex Devices",
    str_detect(name, "(?i)Alloderm") ~ "AlloDerm",
    str_detect(name, "^(?i)Titan |^(?i)Titan$") ~ "Titan",
    str_detect(name, "^(?i)miloop") ~ "miLOOP",
    TRUE ~ name)
  )
